### ISSUE TITLE
Add support of Bear Theme

### ISSUE THREAD

**Issue by Kol9yN** [jeff-hykin/better-dockerfile-syntax#15]
Bear is best theme for eye saving, please can you add support of it?
Thank you so much!

https://marketplace.visualstudio.com/items?itemName=dahong.theme-bear

https://github.com/shaodahong/theme-bear

**Comment by jeff-hykin** [comment]
Sadly that's not something this codebase is capable of :/
Grammars create hooks, and then themes "grab" those hooks.

I can't force the theme to grab [the hooks that are created by this grammar file](https://github.com/jeff-hykin/better-dockerfile-syntax/blob/master/language_tags/dockerfile.txt)
The codebase of the theme needs to change

Seeing as that theme hasn't been updated in 4 years, you'll probably have to fork it.

That link above is all of the hooks (VS Code / Textmate calls them "scopes") provided by this grammar. If you add some of those to [this file (from that theme)](https://github.com/shaodahong/theme-bear/blob/master/themes/bear-color-theme.json) then it should work

**Comment by Kol9yN** [comment]
I already add same comment in theme hub too.
https://github.com/shaodahong/theme-bear/issues/29
